// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Analyzes the credibility of content (text or a link) using AI.
 *
 * - analyzeContentCredibility - A function that analyzes the credibility of content.
 * - AnalyzeContentCredibilityInput - The input type for the analyzeContentCredibility function.
 * - AnalyzeContentCredibilityOutput - The return type for the analyzeContentCredibility function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeContentCredibilityInputSchema = z.object({
  content: z.string().describe('The text or link to analyze for credibility.'),
});
export type AnalyzeContentCredibilityInput = z.infer<typeof AnalyzeContentCredibilityInputSchema>;

const AnalyzeContentCredibilityOutputSchema = z.object({
  credibilityScore: z.number().describe('A score indicating the credibility of the content (0-1).'),
  explanation: z.string().describe('A detailed explanation of the credibility analysis, highlighting specific aspects that contribute to the assessment.'),
  flags: z.array(z.string()).describe('Specific issues or concerns raised by the analysis.'),
});
export type AnalyzeContentCredibilityOutput = z.infer<typeof AnalyzeContentCredibilityOutputSchema>;

export async function analyzeContentCredibility(input: AnalyzeContentCredibilityInput): Promise<AnalyzeContentCredibilityOutput> {
  return analyzeContentCredibilityFlow(input);
}

const analyzeContentCredibilityPrompt = ai.definePrompt({
  name: 'analyzeContentCredibilityPrompt',
  input: {schema: AnalyzeContentCredibilityInputSchema},
  output: {schema: AnalyzeContentCredibilityOutputSchema},
  prompt: `You are an AI assistant designed to analyze the credibility of text or links provided by the user.

  Analyze the following content and determine its credibility score, provide an explanation for the score, and list any specific issues or concerns raised by the analysis.

  Content to analyze: {{{content}}}

  Respond in a JSON format.
  `,
});

const analyzeContentCredibilityFlow = ai.defineFlow(
  {
    name: 'analyzeContentCredibilityFlow',
    inputSchema: AnalyzeContentCredibilityInputSchema,
    outputSchema: AnalyzeContentCredibilityOutputSchema,
  },
  async input => {
    const {output} = await analyzeContentCredibilityPrompt(input);
    return output!;
  }
);
