// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that explains the credibility findings of content.
 *
 * - explainCredibilityFindings - A function that handles the explanation process.
 * - ExplainCredibilityFindingsInput - The input type for the explainCredibilityFindings function.
 * - ExplainCredibilityFindingsOutput - The return type for the explainCredibilityFindings function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainCredibilityFindingsInputSchema = z.object({
  analysis: z.string().describe('The credibility analysis result.'),
  content: z.string().describe('The content that was analyzed.'),
});
export type ExplainCredibilityFindingsInput = z.infer<typeof ExplainCredibilityFindingsInputSchema>;

const ExplainCredibilityFindingsOutputSchema = z.object({
  explanation: z.string().describe('A detailed explanation of the credibility analysis findings.'),
});
export type ExplainCredibilityFindingsOutput = z.infer<typeof ExplainCredibilityFindingsOutputSchema>;

export async function explainCredibilityFindings(input: ExplainCredibilityFindingsInput): Promise<ExplainCredibilityFindingsOutput> {
  return explainCredibilityFindingsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainCredibilityFindingsPrompt',
  input: {schema: ExplainCredibilityFindingsInputSchema},
  output: {schema: ExplainCredibilityFindingsOutputSchema},
  prompt: `You are an AI assistant that explains the credibility findings of content.

  You will be provided with a credibility analysis result and the content that was analyzed. Your task is to provide a detailed explanation of the findings, highlighting specific aspects that contribute to the assessment and explaining clearly what raised alarms for the system.

  Credibility Analysis Result: {{{analysis}}}

  Content: {{{content}}}

  Explanation:`,
});

const explainCredibilityFindingsFlow = ai.defineFlow(
  {
    name: 'explainCredibilityFindingsFlow',
    inputSchema: ExplainCredibilityFindingsInputSchema,
    outputSchema: ExplainCredibilityFindingsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
