// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  "projectId": "studio-1549450926-ce0f4",
  "appId": "1:191259369818:web:5eccad53e43f83458d5363",
  "apiKey": "AIzaSyDNu4a98p1gclAJ8qXtt04tGyZ-dV7DKhw",
  "authDomain": "studio-1549450926-ce0f4.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "191259369818"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
